"""Build the Streamlit secrets files from your .env (run on your own computer).

- Creates ENCRYPTION_KEY and COOKIE_SECRET once and appends them to .env
  (they must stay the same forever, or saved API keys can't be decrypted).
- Writes .streamlit/secrets.toml        -> used when you run the app locally
- Writes .streamlit/secrets.cloud.toml  -> paste its content into Streamlit Cloud
Both files are in .gitignore and never go to GitHub.

Usage:  python scripts/make_secrets.py [--cloud-url https://game-review-radar.streamlit.app]
"""
import argparse
import secrets as pysecrets
from pathlib import Path

from cryptography.fernet import Fernet
from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".env"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cloud-url", default="https://game-review-radar.streamlit.app")
    args = parser.parse_args()

    env = dotenv_values(ENV)
    additions = []
    if not env.get("ENCRYPTION_KEY"):
        env["ENCRYPTION_KEY"] = Fernet.generate_key().decode()
        additions.append(f"ENCRYPTION_KEY={env['ENCRYPTION_KEY']}")
    if not env.get("COOKIE_SECRET"):
        env["COOKIE_SECRET"] = pysecrets.token_urlsafe(32)
        additions.append(f"COOKIE_SECRET={env['COOKIE_SECRET']}")
    if additions:
        with open(ENV, "a", encoding="utf-8") as f:
            f.write("\n# Generated by scripts/make_secrets.py - never change or share these\n")
            f.write("\n".join(additions) + "\n")
        print("Added ENCRYPTION_KEY / COOKIE_SECRET to .env")

    missing = [k for k in ("DATABASE_URL", "GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET",
                           "ADMIN_EMAILS") if not env.get(k)]
    if missing:
        raise SystemExit(f"Missing in .env: {', '.join(missing)}")

    def toml(redirect: str, include_server_values: bool) -> str:
        lines = []
        if include_server_values:
            for key in ("DATABASE_URL", "ADMIN_EMAILS", "ENCRYPTION_KEY", "GEMINI_API_KEY"):
                if env.get(key):
                    lines.append(f'{key} = "{env[key]}"')
            lines.append("")
        lines += [
            "[auth]",
            f'redirect_uri = "{redirect}/oauth2callback"',
            f'cookie_secret = "{env["COOKIE_SECRET"]}"',
            "",
            "[auth.google]",
            f'client_id = "{env["GOOGLE_CLIENT_ID"]}"',
            f'client_secret = "{env["GOOGLE_CLIENT_SECRET"]}"',
            'server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"',
        ]
        return "\n".join(lines) + "\n"

    folder = ROOT / ".streamlit"
    folder.mkdir(exist_ok=True)
    (folder / "secrets.toml").write_text(toml("http://localhost:8501", False))
    (folder / "secrets.cloud.toml").write_text(toml(args.cloud_url.rstrip("/"), True))
    print("Wrote .streamlit/secrets.toml (local) and .streamlit/secrets.cloud.toml (for the cloud)")


if __name__ == "__main__":
    main()
